"""Export-pack framework — one passport, many regulator documents (spec §4).

The rule: **a new regulation is a new renderer, never a new product.** Each pack
maps the same passport into the sections a given regulator/buyer expects. Packs
are registered by name with a tier; ``model-card`` is free, the rest are gated.

A pack implements :func:`Pack.render(passport) -> str` (Markdown). Missing
evidence is surfaced honestly as ``_not attested_`` — we never fabricate a filled
section (Rule §3). Texts say **audit-ready**, never "compliant".
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Optional

# Shared, honest placeholder for evidence that is absent/unattested.
NOT_ATTESTED = "_not attested — evidence not present in this passport_"

AUDIT_READY_FOOTER = (
    "\n---\n\n"
    "_Generated by Soup from a signed Model Passport. This document is "
    "**audit-ready** evidence assembled from cryptographically verifiable run "
    "records. It is not a certification, not legal advice, and not a statement "
    "that any regulator has reviewed or recognised this model. Fields marked "
    "_not attested_ were not established by the underlying evidence._"
)


@dataclass
class Pack:
    name: str
    tier: str  # "free" | "pro" | "enterprise"
    title: str
    description: str
    render: Callable[[dict], str]

    def feature_key(self) -> Optional[str]:
        """License feature required, or None for a free pack."""
        return None if self.tier == "free" else f"pack:{self.name}"


_REGISTRY: dict[str, Pack] = {}


def register(pack: Pack) -> Pack:
    _REGISTRY[pack.name] = pack
    return pack


def get_pack(name: str) -> Pack:
    if name not in _REGISTRY:
        raise KeyError(name)
    return _REGISTRY[name]


def all_packs() -> list[Pack]:
    return sorted(_REGISTRY.values(), key=lambda p: (p.tier != "free", p.name))


# --------------------------------------------------------------------------- #
# Small helpers shared by every renderer
# --------------------------------------------------------------------------- #
def na(value: Any) -> str:
    """Return ``str(value)`` unless it is empty/None — then the honest placeholder."""
    return NOT_ATTESTED if value in (None, "", [], {}) else str(value)


def field(passport: dict, path: str, default: Any = None) -> Any:
    """Dotted lookup into the passport; ``default`` if any hop is missing."""
    cur: Any = passport
    for part in path.split("."):
        if isinstance(cur, dict) and part in cur:
            cur = cur[part]
        else:
            return default
    return cur


def attested_or(passport: dict, path: str, value: Any) -> str:
    """Return ``str(value)`` unless ``path`` is in unattested_fields / value is None."""
    if value in (None, "", [], {}):
        return NOT_ATTESTED
    return str(value)


def header(passport: dict, doc_title: str) -> list[str]:
    """Standard document header lines for a pack."""
    model = passport.get("model", {})
    signer = field(passport, "blocks.accountability.signer", {}) or {}
    return [
        f"# {doc_title}",
        "",
        f"**Model:** {model.get('name')} v{model.get('version')}  ",
        f"**Provenance class:** {passport.get('provenance_class')}  ",
        f"**Signed by:** {signer.get('label') or signer.get('type') or 'self'}  ",
        f"**Passport root hash:** `{field(passport, 'hash_chain.root_hash')}`  ",
        f"**Generated:** {model.get('created_at')}",
        "",
    ]


def render_pack(name: str, passport: dict) -> str:
    """Render a registered pack by name."""
    return get_pack(name).render(passport)
